/**
 * Mock data for development and testing.
 * Represents sample listings from various marketplaces.
 */

export const mockListings = [
  {
    id: "ss-1",
    source: "ss",
    sourceName: "SS.lv",
    url: "https://www.ss.lv/msg/example-1",
    title: "Vintage Bicycle in Great Condition",
    priceText: "150 €",
    priceValue: 150,
    currency: "EUR",
    conditionText: "Good as New",
    postedAtText: "Dec 20, 2024",
    hasDescription: true,
    hasImage: true,
  },
  {
    id: "okidoki-1",
    source: "okidoki",
    sourceName: "Okidoki",
    url: "https://www.okidoki.ee/item/example-1",
    title: "MacBook Pro 2019 - Barely Used",
    priceText: "850 €",
    priceValue: 850,
    currency: "EUR",
    conditionText: "Good as New",
    postedAtText: "Dec 22, 2024",
    hasDescription: true,
    hasImage: true,
  },
  {
    id: "tori-1",
    source: "tori",
    sourceName: "Tori",
    url: "https://www.tori.fi/listing/example-1",
    title: "Comfortable Grey Sofa",
    priceText: "320 €",
    priceValue: 320,
    currency: "EUR",
    conditionText: "Used",
    postedAtText: "Dec 18, 2024",
    hasDescription: false,
    hasImage: true,
  },
  {
    id: "vinted-1",
    source: "vinted",
    sourceName: "Vinted (LT)",
    url: "https://www.vinted.lt/item/example-1",
    title: "Canon EOS Camera with Lenses",
    priceText: "450 €",
    priceValue: 450,
    currency: "EUR",
    conditionText: "Used",
    postedAtText: "Dec 25, 2024",
    hasDescription: true,
    hasImage: true,
  },
  {
    id: "ss-2",
    source: "ss",
    sourceName: "SS.lv",
    url: "https://www.ss.lv/msg/example-2",
    title: "IKEA Dining Table with 4 Chairs",
    priceText: "180 €",
    priceValue: 180,
    currency: "EUR",
    conditionText: "Good as New",
    postedAtText: "Dec 21, 2024",
    hasDescription: true,
    hasImage: false,
  },
  {
    id: "okidoki-2",
    source: "okidoki",
    sourceName: "Okidoki",
    url: "https://www.okidoki.ee/item/example-2",
    title: "iPhone 13 Pro 128GB - Excellent Condition",
    priceText: "650 €",
    priceValue: 650,
    currency: "EUR",
    conditionText: "Good as New",
    postedAtText: "Dec 23, 2024",
    hasDescription: true,
    hasImage: true,
  },
  {
    id: "tori-2",
    source: "tori",
    sourceName: "Tori",
    url: "https://www.tori.fi/listing/example-2",
    title: "PlayStation 5 with 2 Controllers",
    priceText: "420 €",
    priceValue: 420,
    currency: "EUR",
    conditionText: "Used",
    postedAtText: "Dec 19, 2024",
    hasDescription: true,
    hasImage: true,
  },
  {
    id: "ss-3",
    source: "ss",
    sourceName: "SS.lv",
    url: "https://www.ss.lv/msg/example-3",
    title: "Samsung 55 4K Smart TV",
    priceText: "380 €",
    priceValue: 380,
    currency: "EUR",
    conditionText: "Used",
    postedAtText: "Dec 24, 2024",
    hasDescription: false,
    hasImage: true,
  },
];
